### ISSUE TITLE
Does not compile for arm64 simulator if the project also uses Swift Package Manager

### ISSUE THREAD

**Issue by tikitu** [opentok/opentok-ios-sdk-samples-swift#195]
**Describe the bug**
The setting `"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64;` from the OpenTok pod is incompatible with SPM packages: if a project includes both the OpenTok pod and any SPM package at all, it will fail to build for arm64 simulators (including simulators for recent iOS versions on M1 Macs).

**To Reproduce**
1. Add any SPM package whatsoever to the sample.
2. Import a type from that package
3. Try to build for a recent iOS simulator, on an M1 Mac.

I made an example at https://github.com/tikitu/opentok-ios-sdk-samples-swift/tree/spm-and-m1 importing the SwiftArgumentParser package, just to show my working.

**Expected behavior**
The project should compile. Instead it fails, with the error message `Could not find module 'ArgumentParser' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator`.

**Device (please compete the following information):**
- iOS SDK version: 2.25.0
- OS and version: macOS Monterey 12.6.4
- Xcode version: 14.2 _(not using Rosetta emulation)_

**Additional context**
This is more urgent now that Xcode 14.3 has shipped, as this Xcode version removes support for Rosetta emulation: developers on an M1 Mac must stay with Xcode 14.2 if their project includes both OpenTok and any SPM packages.

There's a related issue asking for SPM support (#130) -- while that would be great, the more significant point for our team is that we cannot use SPM for _other packages_ if we're including the OpenTok pod.

**Comment by emilyvon** [comment]
I'm facing the same issue, adding some screenshots for references. 

In OpenTok pod setting: `EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64` for both debug and release: 
<img width="1656" alt="235587852-592ea372-4a07-4bb3-8002-4b0eb8143df4" src="https://user-images.githubusercontent.com/12323442/235589650-8e7fc88c-4e56-40cb-9a5b-7b057eb1bc77.png">

And if I commented that line out in the generated pod setting file, I ran into another issue: 
<img width="1159" alt="235588361-74bb64e1-cbed-4b83-a869-5439ef37acc0" src="https://user-images.githubusercontent.com/12323442/235589271-165247dd-905a-4c11-ba4b-7e3f503b6472.png">

**Comment by vona-ben** [comment]
Hello, Since 2.24.2 release, we have M1 / arm chipset support. To build on arm chipset based machines, users needs to use OTXCFramewok (version >= 2.24.2)
Example:

```
target 'Basic-Video-Chat' do
pod 'OTXCFramework', OpenTokSDKVersion
end
```
instead off
```
target 'Basic-Video-Chat' do
pod 'Opentok', OpenTokSDKVersion
end
```

**Comment by vona-ben** [comment]
Note: We are working on a SPM for iOS SDK which would be available soon. I will keep you updated in this thread

**Comment by jvalli** [comment]
The issue is because you are trying to use old fat framework on M1 machine(arm64). The old fat framework version cannot have unique build configuration to work on both arm64 & x86_64 simulators, so we were agree that old fat framework version will be distributed with  ["EXCLUDED_ARCHS[sdk=iphonesimulator*]": "arm64"](https://github.com/CocoaPods/Specs/blob/master/Specs/2/d/8/OpenTok/2.25.0/OpenTok.podspec.json#L43)  configuration to be able to use it on Simulator Intel machines(x86_64) by default. If the build configuration is removed it works on Simulator M1 but not on Simulator Intel.

So you can use new XCFramework version available through:
- SPM: https://github.com/opentok/vonage-client-sdk-video.git
- Cocoapods: pod `OTXCFramework`
