### ISSUE TITLE
Is it possible to access both mics simultanesouly using the custom audio driver code?

### ISSUE THREAD

**Issue by sriranjanr** [opentok/opentok-ios-sdk-samples-swift#50]
Hello,

I am looking for ways to access the audio data from two or more mics on the iphone simultaneously. I came across the custom audio driver xcode project here. Is it possible to write an audio driver by modifying the custom audio driver code with which we can access audio data from 2 or more mics simultaneously on the iphone? Please let me know. I have looked at the custom audio driver code and the number of channels are mentioned as 1. Is it possible to label it as 2 and write some code to access multiple mic data at once..?

**Comment by robjperez** [comment]
Hi!

This question is more related with AVFoundation SDK, the audio driver uses that API in order to access to the mics, so it should be iOS the one which allows you to capture audio from different mics at the same time.

From our knowledge, the input device is treated as a single one, and it uses the three mics to improve the performance of the recorded audio. You can however decide which mic will be the "leading" one. Please take a look to [this](https://developer.apple.com/library/content/qa/qa1799/_index.html) link for more information.
