### ISSUE TITLE
[Simple-Multiparty] subscriber shows blank screen after rejoining

### ISSUE THREAD

**Issue by Lucashuang0802** [opentok/opentok-ios-sdk-samples-swift#63]
The app seems to have some issues when one or more subscribers rejoin. Subscriber views show blank screen.

**Comment by ozkansari37** [comment]
I have same problem. I cant find any solutions yet. After the rejoin, subscriber view is black. But if i click mute subscriber button, video shows up.

**Comment by ozkansari37** [comment]
I found the problem. Subscriber view is inserted to collectionview cell inside layoutSubviews method. When subsucriber rejoined, layout is remain same and layoutSubviews never called. Because of that subscriber view never inserted to cell. I inserted subscriber view in dequeueReusableCell method. That fixed the problem.
