### ISSUE TITLE
OTVideoCaptureConsumer consumeFrame crash

### ISSUE THREAD

**Issue by doquanghuy** [opentok/opentok-ios-sdk-samples-swift#67]
I am using your library into our project. I am facing a critical bug relates to consumeFrame function of OTVideoCaptureConsumer. My flow:

1. Create a custom VideoCapture
2. Use GPUImage to filter camera, the camera object of GPUImage has a delegate  func didCaptureBuffer(_ sampleBuffer: CMSampleBuffer) {...}
3. In delegate func didCaptureBuffer, I implement addPointer for videoFrame.planes
4. After addPointer for videoFrame.planes, I call consumeFrame from videoCaptureConsumer. This causes a crash.

Please give me a solution to fix this bug. Thank you so much!

P/s: I attached a error message 
<img width="308" alt="screen shot 2018-06-13 at 5 34 39 pm" src="https://user-images.githubusercontent.com/9291831/41346257-2c88b3fe-6f30-11e8-8832-d8b963e5d192.png">
below.

**Comment by robjperez** [comment]
Hi @doquanghuy 

That usually happens because you specify that your frame contains a planar image (like NV12 or NV21) but actually you send a non-planar image (like ARGB).

Please check the output of `GPUImage`, and change this line: https://github.com/opentok/opentok-ios-sdk-samples-swift/blob/master/Custom-Video-Driver/Lets-Build-OTPublisher/ExampleVideoCapture.swift#L78 accordingly

If GPUImage outputs a ARGB image, you will need to change it to have something like:

`videoFrame = OTVideoFrame(format: OTVideoFormat(argbWithWidth: captureWidth, height: captureHeight))`

**Comment by msach22** [comment]
@doquanghuy I'm assuming @robjperez's comment fixed your issue so I'm going to close the issue. Please re-open if the issue still persists.

**Comment by iobroyles** [comment]
I am also seeking a concrete path of using GPUImage to send filtered frames to OpenTok.

@doquanghuy did you get this working properly? Thanks!

**Comment by iobroyles** [comment]
var videoFrame = OTVideoFrame(format: OTVideoFormat(argbWithWidth: 640, height: 480)) fixed it for me, thanks!
